version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: classroom_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: classroom_reservations
      MYSQL_USER: classroom_user
      MYSQL_PASSWORD: classroom_pass
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
  php:
    build: ./php
    container_name: classroom_php
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=classroom_reservations
      - MYSQL_USER=classroom_user
      - MYSQL_PASSWORD=classroom_pass
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
volumes:
  db_data:
